/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_2_20_02_32/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}

/*
 *  ======== Timer0_B3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_B0_VECTOR
__interrupt void TIMER0_B0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_B0_ISR_HOOK) */
	__low_power_mode_off_on_exit();				// Every second the main loop starts up again
    /* USER CODE END (section: TIMER0_B0_ISR_HOOK) */
}



/*
 *  ======== PORT1 Interrupt Service Routine ========
 *
 * Here are several important notes on using PORT1 interrupt Handler:
 * 1. User could use the following code to efficiently service the interrupt
 *    handler. Just simply copy and paste it into your user definable code
 *    section.

    switch(__even_in_range(P1IV, P1IV_P1IFG7))
    {
        case P1IV_NONE: break;              // Vector 0: No interrupts pending;
        case P1IV_P1IFG0: break;            // Vector 2: P1IFG.0;
        case P1IV_P1IFG1: break;            // Vector 4: P1IFG.1;
        case P1IV_P1IFG2: break;            // Vector 6: P1IFG.2;
        case P1IV_P1IFG3: break;            // Vector 8: P1IFG.3;
        case P1IV_P1IFG4: break;            // Vector 10: P1IFG.4;
        case P1IV_P1IFG5: break;            // Vector 12: P1IFG.5;
        case P1IV_P1IFG6: break;            // Vector 14: P1IFG.6;
        case P1IV_P1IFG7: break;            // Vector 16: P1IFG.7;
        default: break;
    }

 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=PORT1_VECTOR
__interrupt void PORT1_ISR_HOOK(void)
{

    /* USER CODE START (section: PORT1_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: PORT1_ISR_HOOK) */
}
/*
 * ======== Preserved user code snippets ========
 */
#if 0
/* USER CODE START (section: USCI_A1_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: USCI_A1_ISR_HOOK) */
#endif
