/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_2_20_02_32/packages/ti/mcu/msp430/csl2/communication/EUSCI_init.xdt
 */
#include <stdint.h>
#include <driverlib/MSP430FR57xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR57xx/eusci_a_spi.h>

/* USER CODE START (section: EUSCI_A1_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: EUSCI_A1_init_c_prologue) */

/*
 *  ======== EUSCI_A1_graceInit ========
 *  Initialize Config for the MSP430 EUSCI_A1
 */
void EUSCI_A1_graceInit(void)
{

    /* USER CODE START (section: EUSCI_A1_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: EUSCI_A1_graceInit_prologue) */

    /* initialize eUSCI SPI master mode */
    EUSCI_A_SPI_masterInit(EUSCI_A1_BASE, EUSCI_A_SPI_CLOCKSOURCE_SMCLK, 8000000, 1000000,
                    EUSCI_A_SPI_MSB_FIRST, EUSCI_A_SPI_PHASE_DATA_CAPTURED_ONFIRST_CHANGED_ON_NEXT, EUSCI_A_SPI_CLOCKPOLARITY_INACTIVITY_LOW, EUSCI_A_SPI_3PIN);

    /* enable eUSCI SPI */
    EUSCI_A_SPI_enable(EUSCI_A1_BASE);

    /* disable eUSCI SPI transmit interrupt */
    EUSCI_A_SPI_disableInterrupt(EUSCI_A1_BASE, EUSCI_A_SPI_TRANSMIT_INTERRUPT);

    /* disable eUSCI SPI receive interrupt */
    EUSCI_A_SPI_disableInterrupt(EUSCI_A1_BASE, EUSCI_A_SPI_RECEIVE_INTERRUPT);

    /* USER CODE START (section: EUSCI_A1_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: EUSCI_A1_graceInit_epilogue) */

}
